spring: 
  dataSource: 
   type: com.alibaba.druid.pool.DruidDataSource
   driver-class-name: com.oracle.jdbc.Driver.oracleDriver
   url: jdbc:oracle:thin://localhost:1521:ocal
   username: scott
   password: scott
   